# Generated by Django 4.0.2 on 2022-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_voice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='records'),
        ),
    ]
